config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :proposals
  resources :reviews
  resources :votes

  root :to => 'landing_page#index'

  post '/proposal/cancel' => 'proposals#cancel', as: 'cancel_proposal'
  get '/submission_period/toggle' => 'submission_periods#toggle', as: 'toggle_submission_period'
  get '/proposal/vote' => 'proposals#head_vote', as: 'head_vote'
  get '/proposal/veto' => 'proposals#veto', as: 'veto'
  get '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/activate' => 'users#activate', as: 'activate_user'
  get '/users/:id/deactivate' => 'users#deactivate', as: 'deactivate_user'
  get '/proposal/search' => 'proposals#search', as: 'search_proposal'
  resources :announcements, except: [:index]
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def index
      @announcements = Announcement.all
  end

  def show
    authorize! :show, Announcement
    @announcement = Announcement.find(params[:id])
  end

  def new
    authorize! :create, Announcement
    @announcement = Announcement.new
  end

  def edit
    authorize! :edit, Announcement
    @announcement = Announcement.find(params[:id])
  end

  def create
    authorize! :create, Announcement
    
    @announcement = Announcement.new(announcement_params)

    if params[:commit] == "Save as Draft"
      @announcement.isDraft = true
    elsif params[:commit] == "Submit"
      @announcement.isDraft = false
    end

    if @announcement.save
      redirect_to :root
    else
      render 'new'
    end
  end

  def update
    authorize! :edit, Announcement
    
    @announcement = Announcement.find(params[:id])

    if params[:commit] == "Save as Draft"
      @announcement.isDraft = true
    elsif params[:commit] == "Submit"
      if @announcement.isDraft
        @announcement.isDraft = true
        @announcement.created_at = Time.now
      end
      @announcement.isDraft = false
    end

    if @announcement.update(announcement_params)
      redirect_to :root
    else
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, Announcement
    
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    redirect_to :root
  end

  private
    def announcement_params
      params.require(:announcement).permit(:title, :text, :isDraft)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, html: { class: 'ui form' } do |f| %>

  <% if @announcement.errors.any? %>
    <div id="error_explanation" class="ui message">
      <h2 class="ui header">
        <%= pluralize(@announcement.errors.count, "error") %> prohibited
        this announcement from being submitted:
      </h2>
      <ul class="ui list">
        <% @announcement.errors.full_messages.each do |msg| %>
          <li class="item"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="required field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

    <div class="required field">
      <%= f.label :text, "Content"%>
      <%= f.text_area :text, placeholder: "Content of Announcement" %>
    </div>

    <% if @announcement.isDraft.nil? || @announcement.isDraft %>
    <div class="field">
        <div class="ui mini buttons">
          <%= f.submit "Save as Draft", class: "ui button"%>
          <div class="or"></div>
          <%= f.submit "Submit", class: "ui positive button" %>
        </div>
    </div>
    <% else %>
    <%= f.submit "Submit", class: "ui positive button" %>
    <% end %>

<% end %>

app/views/announcements/edit.html.erb
<div class="ui text container">
    <h1 class="ui header center aligned">Edit Announcement</h1>
    <div class="ui segment center aligned" style="margin-bottom: 10px;">
        <%= render 'form' %>
    </div>
</div>

app/views/announcements/index.html.erb
<h1>Announcement List</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>

  <% @announcements.each do |announcement| %>
    <tr>
      <td><%= announcement.title %></td>
      <td><%= link_to 'Show', announcement_path(announcement) %></td>
      <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
      <td><%= link_to 'Delete', announcement_path(announcement),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/announcements/new.html.erb
<div class="ui text container">
    <h1 class="ui header center aligned">Create Announcement</h1>
    <div class="ui segment center aligned" style="margin-bottom: 10px;">
        <%= render 'form' %>
    </div>
</div>

app/views/announcements/show.html.erb
<p>
  <strong>Announcement Title: </strong>
  <%= @announcement.title %>
</p>

<p>
  <%= @announcement.text %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>