config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :proposals
  resources :reviews
  resources :votes

  root :to => 'landing_page#index'

  post '/proposal/cancel' => 'proposals#cancel', as: 'cancel_proposal'
  get '/submission_period/toggle' => 'submission_periods#toggle', as: 'toggle_submission_period'
  get '/proposal/vote' => 'proposals#head_vote', as: 'head_vote'
  get '/proposal/veto' => 'proposals#veto', as: 'veto'
  get '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/activate' => 'users#activate', as: 'activate_user'
  get '/users/:id/deactivate' => 'users#deactivate', as: 'deactivate_user'
  get '/proposal/search' => 'proposals#search', as: 'search_proposal'
  resources :announcements, except: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new
    if user.type == "Researcher"
      can :index, Proposal, user_id: user.id
      can :read, Proposal, user_id: user.id
      if SubmissionPeriod.first.active && !user.submitted
        can :create, Proposal
        can :new, Proposal
        can :update, Proposal, is_draft: true
      end
      can :cancel, Proposal, is_draft: true
      can :cancel, Proposal, status: 0
    elsif user.type == "CommitteeMember"
      can :index, Proposal, is_draft: false
      can :read, Proposal, is_draft: false
      can :create, Review
      can :read, Review, user_id: user.id
      cannot :index, Proposal, status: -2
    elsif user.type == "CommitteeHead"
      can :index, Proposal, is_draft: false
      can :read, Proposal, is_draft: false      
      can :toggle, SubmissionPeriod
      can :edit, Proposal, is_draft: false 
      can :vote, Proposal, is_draft: false
      can :read, Review
      can :create, Announcement
      can :edit, Announcement
      can :destroy, Announcement
      cannot :index, Proposal, status: -2
    elsif user.type == "Dean"
      can :index, Proposal, head_vote: 2
      can :read, Proposal, head_vote: 2
      can :veto, Proposal, head_vote: 2
      cannot :index, Proposal, status: -2
    elsif user.type == "Admin"
      can :index, User
      can :show, User
      can :activate, User
      can :deactivate, User
    else
      can :index, Proposal, status: 2
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/committee_head.rb
class CommitteeHead < User
end

app/models/committee_member.rb
class CommitteeMember < User

end

app/models/dean.rb
class Dean < User
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  before_create :set_status

  validates :title, presence: true
  validates :rdCost, presence: true, numericality: { only_float: true }
  validates_numericality_of :rdCost, greater_than_or_equal_to: 0, less_than_or_equal_to: 5000000
  validates :objectives, presence: true
  validates :principal_researcher, presence: true
  validates :expectedOutputs, presence: true
  validates :description, presence: true
  validates :weeklyHours, presence: true
  validates :endorsement, :inclusion => {:in => [true, false]}
  validates :submitAgency, :inclusion => {:in => [true, false]}
  validates :attachment, presence: true
  validates :recommendation, presence: true

  mount_uploader :attachment, AttachmentUploader
  mount_uploader :recommendation, RecommendationUploader

  belongs_to :user
  has_many :reviews

  def set_status
    self.status = 0
  end
end

app/models/researcher.rb
class Researcher < User

end

app/models/review.rb
class Review < ApplicationRecord
  # validates :attachment, presence: true
  mount_uploader :attachment, AttachmentUploader
  belongs_to :proposal
  belongs_to :user
end

app/models/submission_period.rb
class SubmissionPeriod < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_user_type, :set_activated
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  devise :timeoutable, timeout_in: 15.minutes
  has_many :proposals
  has_many :reviews

  validates :first_name, :last_name, :rank, :department, :contact_number, presence: true

  def set_user_type
    self.type ||= 'Researcher'
  end

  def set_activated
    if self.type == 'Admin' || self.type == 'CommitteeHead' || self.type == 'CommitteeMember' || self.type == 'Dean'
      self.write_attribute(:activated?, true)
    else
      self.write_attribute(:activated?, false)
    end
  end

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
      @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    authorize! :create, Review
    @review = Review.new(review_params)
    if current_user.reviews.where('proposal_id = ?', @review.proposal_id).length > 0
      flash[:negative] = "You can only give a review once per proposal"
      redirect_to :back and return
    end
    @review.user_id = current_user.id

    if params[:commit] == "Reject"
      @review.vote = -1
    elsif params[:commit] == "Accept"
      @review.vote = 2
    elsif params[:commit] == "Resubmit"
      @review.vote = 1
    end
    
    @review.save

    redirect_to :back
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to reviews_path
  end

  private
    def review_params
      params.require(:review).permit(:attachment, :vote, :comment, :proposal_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        authorize! :show, User
        @user = User.find(params[:id])
    end

    def activate
        @user = User.find(params[:id])
        authorize! :activate, @user
    
        @user.update(activated?: true)
        @user.save

        redirect_to :root
    end

    def deactivate
        @user = User.find(params[:id])
        authorize! :deactivate, @user

        if @user.type == 'Researcher'
            @user.update(activated?: false)
            @user.save
        end 
        
        redirect_to :root
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
      @votes = Vote.all
  end

  def show
    @vote = Vote.find(params[:id])
  end

  def new
    @vote = Vote.new
  end

  def edit
    @vote = Vote.find(params[:id])
  end

  def create
    @vote = Vote.new(vote_params)

    if @vote.save
      redirect_to @vote
    else
      render 'new'
    end
  end

  def update
    @vote = Vote.find(params[:id])

    if @vote.update(vote_params)
      redirect_to @vote
    else
      render 'edit'
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    redirect_to vote_path
  end

  private
    def vote_params
      params.require(:vote).permit(:decision)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admin/admin_accounts.html.erb
<div class="ui padded container segment">
    <div class="ui segment">
        <div class="ui medium header">
            Accounts
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 1
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>   
                 </div>
            </div>
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 2
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>
                 </div>
            </div>
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 3
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>
                 </div>
            </div>
        </div>
    </div>
</div>
   

app/views/admin/admin_home.html.erb
<div class="ui container grid">
    <div class="row">
        <div class="ten wide column right bordered">
            <div class="ui segment">
                <div class="ui huge header">
                    Announcements
                </div>
                <div class="ui celled feed">
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header 
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="six wide column">
            <div class="ui basic segment center aligned">
                <div class="ui statistic">
                    <div class="value">
                        5:30 PM
                    </div>
                    <div class="label">
                        UP Official Time
                    </div>
                </div>
            </div>
            <div class="ui basic attached segment">
                <div class="ui header center aligned">
                  Pending Accounts <!--edited-->
                </div>
                <div class="ui selection celled list">
                    <div class="item">
                        <div class="content">
                            <div class="header">User 1</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                    <div class="item">
                        <div class="content">
                            <div class="header">User 2</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                    <div class="item">
                        <div class="content">
                            <div class="header">User 3</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui button bottom orange attached"> <!---edited-->  
                See more pending accounts ->
            </div>
        </div>
    </div>
</div>

app/views/admin/home.html.erb
<div class="ui container grid center aligned">
    <div class="row">
        <div class="fourteen wide column">
            <div class="ui basic segment">
                <div class="ui medium header">
                    Users
                </div>
                <table class="ui orange striped selectable celled table">
                  <thead>
                    <tr><th>Email</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th class="five wide">Actions</th>
                  </tr></thead>
                  <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td><%= user.email %></td>
                        <td><%= user.type %></td>
                        <td>
                            <% if user.activated? && user.type == 'Researcher' %>
                            Activated
                            <% elsif !user.activated? && user.type == 'Researcher' %>
                            Deactivated
                            <% else %>
                            N/A
                            <% end %>
                        </td>
                        <td>
                            <% if can? :show, user %>
                                <%= link_to 'View', show_user_path(user), class: 'ui button orange mini' %>
                            <% end %>
                            <% if can?(:activate, user) && !user.activated? && user.type == 'Researcher' %>
                                <%= link_to 'Activate', activate_user_path(user), class: 'ui button green mini' %>
                            <% end %>
                            <% if can?(:deactivate, user) && user.activated? && user.type == 'Researcher' %>
                                <%= link_to 'Deactivate', deactivate_user_path(user), class: 'ui red button mini', data: { confirm: "Are you sure to deactivate #{user.email}?"} %>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/camille/new/AdminAccounts.html.erb
<div class="ui padded container segment">
    <div class="ui segment">
        <div class="ui medium header">
            Accounts
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 1
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>   
                 </div>
            </div>
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 2
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>
                 </div>
            </div>
        </div>
        <div class="ui celled feed">
            <div class="event">
                <div class="content">
                    <div class="summary">
                         User 3
                    </div>
                    <div class="extra text">
                        Rank, Department
                    </div>
                    <div class="ui primary button">
                        Activate
                    </div>
                    <div class="ui button">
                        Discard
                    </div>
                 </div>
            </div>
        </div>
    </div>
</div>
   

app/views/camille/new/AdminHome.html.erb
<div class="ui container grid">
    <div class="row">
        <div class="ten wide column right bordered">
            <div class="ui segment">
                <div class="ui huge header">
                    Announcements
                </div>
                <div class="ui celled feed">
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header 
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                Announcement Header
                            </div>
                            <div class="meta">
                                <div class="date">April 10, 2016 8:30PM PHT</div>
                            </div>
                            <div class="extra text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab culpa ratione minus facilis quae autem illum, qui assumenda voluptatem, hic vitae ad aliquam id cumque maiores, non veritatis doloremque laborum.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="six wide column">
            <div class="ui basic segment center aligned">
                <div class="ui statistic">
                    <div class="value">
                        5:30 PM
                    </div>
                    <div class="label">
                        UP Official Time
                    </div>
                </div>
            </div>
            <div class="ui basic attached segment">
                <div class="ui header center aligned">
                  Pending Accounts <!--edited-->
                </div>
                <div class="ui selection celled list">
                    <div class="item">
                        <div class="content">
                            <div class="header">User 1</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                    <div class="item">
                        <div class="content">
                            <div class="header">User 2</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                    <div class="item">
                        <div class="content">
                            <div class="header">User 3</div> <!---edited-->  
                            <div class="description">
                                Rank, Department
                            </div>
                            <div class="ui button" >Accept</div> 
                            <div class="ui button" >Reject</div> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui button bottom orange attached"> <!---edited-->  
                See more pending accounts ->
            </div>
        </div>
    </div>
</div>

app/views/shared/_flash.html.erb
<div class="ui container" style="margin-bottom: 18px;">
    <% flash.each do |key, value| %>
        <% next if key == 'timedout' %>
        <div class="ui <%= key %> message">
        <i class="close icon"></i>
        <p><%= value %></p>
        </div>
    <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="ui container grid">
    <div class="row">
        <div class="sixteen wide column">
            <div class="ui header tiny center aligned">
                    <div class="sub header">
                        &copy; University of the Philippines Diliman – College of Engineering 2017
                    </div>
                </div>
        </div>
    </div>
</footer>

app/views/shared/_nav.html.erb
<div class="ui fixed menu borderless" style="height: 110px; z-index: 11;">
	<div class="ui container">
		<div class="left menu">
			<%= link_to root_path, class: 'item brand' do %>
				<%= image_tag 'coe_logo.png', class: 'ui tiny middle aligned image' %>
				<h1 class="ui header white spaced">
					FRIA
					<div class="sub header white">
					Faculty Research Incentive Award
					</div>
				</h1>
			<% end%>
		</div>
		<div class="right menu">
			<% if not user_signed_in? %>
				<%= form_for(@user, :url => session_path(@user), :html => {class: "ui form", id: "login"}) do |f| %>
					<div class="fields">
						<div class="field">
							<%= f.label :email %>
							<%= f.email_field :email, autofocus: true, placeholder: "Email" %>
						</div>
						<div class="field">
							<%= f.label :password %>
							<%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
						</div>
						<%= f.submit "Login", class: "ui button", id: "login_button" %>
					</div>
				<% end %>
			<% else %>
				<div class="item white">
					Hello, <%= "#{current_user.first_name} #{current_user.last_name}" %>
				</div>
				<div class="ui secondary menu">
					<%= link_to 'Home', root_path, class: 'item white' %>
					<% if can? :create, Proposal %>
						<div class="ui dropdown item white">
							Proposals
							<i class="dropdown icon"></i>
							<div class="menu">
								<%= link_to('Proposals', proposals_path, class: 'item white') %>
								<%= link_to('Submit Proposal', new_proposal_path, class: 'item white') %>
							</div>
						</div>
					<% elsif current_user.type == 'Admin' %>
					<% else %>
						<%= link_to('Proposals', proposals_path, class: 'item white') %>
					<% end %>
					<% # <a class="item white">Settings</a> %>
					<a> 
						<%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'item white', id: 'logout_button') %>  
					</a>
				</div>
			<% end %>
		</div>
	</div>
</div>
<%- # this is for the buffer of the nav bar. %>
<div style="margin-top: 126px;"></div>
<% if current_user && !current_user.activated? %>
	<div class="ui inline nag fixed" style="background-color: #d24536; margin-top: 110px; z-index: 10;">
  <span class="title">
    Your account is yet to be activated. Please contact us if you think this should not be an error.
  </span>
</div>
<div style="margin-top: 160px;"></div>
<% end %>

<script>
	$('.nag').nag('show');
</script>