config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :proposals
  resources :reviews
  resources :votes

  root :to => 'landing_page#index'

  post '/proposal/cancel' => 'proposals#cancel', as: 'cancel_proposal'
  get '/submission_period/toggle' => 'submission_periods#toggle', as: 'toggle_submission_period'
  get '/proposal/vote' => 'proposals#head_vote', as: 'head_vote'
  get '/proposal/veto' => 'proposals#veto', as: 'veto'
  get '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/activate' => 'users#activate', as: 'activate_user'
  get '/users/:id/deactivate' => 'users#deactivate', as: 'deactivate_user'
  get '/proposal/search' => 'proposals#search', as: 'search_proposal'
  resources :announcements, except: [:index]
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  before_create :set_status

  validates :title, presence: true
  validates :rdCost, presence: true, numericality: { only_float: true }
  validates_numericality_of :rdCost, greater_than_or_equal_to: 0, less_than_or_equal_to: 5000000
  validates :objectives, presence: true
  validates :principal_researcher, presence: true
  validates :expectedOutputs, presence: true
  validates :description, presence: true
  validates :weeklyHours, presence: true
  validates :endorsement, :inclusion => {:in => [true, false]}
  validates :submitAgency, :inclusion => {:in => [true, false]}
  validates :attachment, presence: true
  validates :recommendation, presence: true

  mount_uploader :attachment, AttachmentUploader
  mount_uploader :recommendation, RecommendationUploader

  belongs_to :user
  has_many :reviews

  def set_status
    self.status = 0
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @proposal_status = ['Pending', 'Resubmit', 'Accepted', 'Cancelled', 'Rejected']
    authorize! :index, Proposal
    @proposals = Proposal.accessible_by(current_ability).order('id DESC')
  end

  def show
    @proposal = Proposal.find(params[:id])
    authorize! :read, @proposal

    if current_user.type == 'CommitteeMember'
      @review = Review.new
      @current_review = @proposal.reviews.where('user_id = ?', current_user.id).first
    elsif current_user.type == 'CommitteeHead'
      @reviews = @proposal.reviews
    end

  end

  def new
    @proposal = Proposal.new
    authorize! :new, @proposal
  end

  def edit
    @proposal = Proposal.find(params[:id])
    authorize! :update, @proposal
  end

  def create
    @proposal = Proposal.new(proposal_params)
    authorize! :create, @proposal

    if !current_user.activated?
      @proposal.is_draft = true
      @proposal.save
      redirect_to @proposal
      return
    end

    if params[:commit] == "Save as Draft"
      @proposal.is_draft = true
    elsif params[:commit] == "Submit" && !current_user.submitted
      @proposal.is_draft = false
      current_user.submitted = true
      current_user.save
    elsif params[:commit] == "Submit" && current_user.submitted
      flash[:negative] = "You have already submitted a proposal this submission period."
    end
    
    if @proposal.save
      redirect_to @proposal
    else
      render 'new'
    end
  end

  def update
    @proposal = Proposal.find(params[:id])

    if params[:commit] == "Save as Draft"
      @proposal.is_draft = true
    elsif params[:commit] == "Submit"
      @proposal.is_draft = false
      current_user.submitted = true
      current_user.save
    end

    if @proposal.update(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def cancel
    @proposal = Proposal.find(params[:id])
    authorize! :cancel, @proposal
    @proposal.update_attribute(:status, -2)
    @proposal.update_attribute(:is_draft, false)

    redirect_to proposals_path
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    redirect_to proposals_path
  end

  def head_vote
    @proposal = Proposal.find(params[:proposal_id])
    authorize! :vote, @proposal
    if params[:vote] == "Accept"
      @proposal.head_vote = 2
    elsif params[:vote] == "Resubmit"
      @proposal.status = 1
      @proposal.head_vote = 1
    elsif params[:vote] == "Reject"
      @proposal.status = -1
      @proposal.head_vote = -1
    end

    @proposal.save
    redirect_to :back
  end

  def veto
    @proposal = Proposal.find(params[:proposal_id])
    authorize! :veto, @proposal
    if params[:vote] == "Accept"
      @proposal.status = 2
    elsif params[:vote] == "Reject"
      @proposal.status = -1
    end

    @proposal.save
    redirect_to :back
  end

  def search
    key = params[:search]
    @proposals = Proposal.where('title ILIKE ? OR principal_researcher ILIKE ?', "%#{key}%", "%#{key}%").where(status: 2)
    render 'index'
  end

  private
    def proposal_params
      params.require(:proposal).permit(:title, :principal_researcher, :coresearchers, :rdCost, :sourceExternal, :amountExternal, :facMat, :objectives, :expectedOutputs, :description, :weeklyHours, :endorsement, :submitAgency, :listAgency, :attachment, :status, :user_id, :recommendation)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_for @proposal, html: { class: 'ui form' } do |f| %>

  <% if @proposal.errors.any? %>
    <div id="error_explanation" class="ui message">
      <h2 class="ui header">
        <%= pluralize(@proposal.errors.count, "error") %> prohibited
        this proposal from being submitted:
      </h2>
      <ul class="ui list">
        <% @proposal.errors.full_messages.each do |msg| %>
          <li class="item"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="required field">
    <%= f.label :title, "Title of Project" %>
    <%= f.text_field :title, placeholder: "Title of Project" %>
  </div>

    <div class="required field">
      <%= f.label :principal_researcher, "Principal Researcher"%>
      <%= f.text_field :principal_researcher, placeholder: "Principal Researcher" %>
    </div>

    <div class="field">
      <%= f.label :coresearchers, "Name of Coresearchers"%>
      <%= f.text_area :coresearchers, placeholder: "Name of Coresearchers" %>
    </div>

  <div class="three fields">
    <div class="field required">
      <%= f.label :rdCost, "Total Research and Development Cost"%>
      <%= f.number_field :rdCost, placeholder: "Total Research and Development Cost", step: 1 %>
    </div>

    <div class="field">
      <%= f.label :sourceExternal, "Source of External Funds"%>
      <%= f.text_field :sourceExternal, placeholder: "Source of External Funds" %>
    </div>

    <div class="field">
      <%= f.label :amountExternal, "Amount of External Funds"%>
      <%= f.text_field :amountExternal, placeholder: "Amount of External Funds" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :facMat, "Facilities, Materials, Staff within the Department or College (if any)"%>
    <%= f.text_area :facMat, placeholder: "Facilities, Materials, Staff within the Department or College (if any)" %>
  </div>

  <div class="two fields">
    <div class="required field">
      <%= f.label :objectives, "Objectives of the Project"%>
      <%= f.text_area :objectives, placeholder: "Objectives of the Project" %>
    </div>
    <div class="required field">
      <%= f.label :expectedOutputs, "Expected Outputs"%>
      <%= f.text_area :expectedOutputs, placeholder: "Expected Outputs" %>
    </div>
  </div>

  <div class="required field">
    <%= f.label :description, "Description of Work Done and Accomplishemnts (if project is in progress)"%>
    <%= f.text_area :description, placeholder: "Description of Work Done and Accomplishments (if project is in progress)" %>
  </div>

  <div class="required field">
    <%= f.label :weeklyHours, "Estimated Number of Hours Per Week Devoted to this Project"%>
    <%= f.number_field :weeklyHours, placeholder: "Estimated Number of Hours Per Week Devoted to this Project", step: 1 %>
  </div>

  <div class="field">
    <div class="ui checkbox">
      <%= f.check_box :endorsement %>
      <%= f.label :endorsement, "Have you attained endorsement from Department Head/Chairman?"%>
    </div>
  </div>

<div class="field">
  <div class="ui checkbox">
    <%= f.check_box :submitAgency %>
    <%= f.label :submitAgency, "Have you submitted this proposal to any other funding agency?"%>
  </div>
</div>

<div class="field">
  <%= f.label :listAgency, "If yes, please state the agencies" %>
  <%= f.text_area :listAgency, placeholder: "List of Agencies" %>
</div>

  <div class="required field">
    <%= f.label :attachment, "Upload Proposal (PDF)"%>
    <%= f.file_field :attachment, accept: '.pdf' %>
  </div>

  <div class="required field">
    <%= f.label :recommendation, "Upload Recommendation (PDF)"%>
    <%= f.file_field :recommendation, accept: '.pdf' %>
  </div>
    <% if current_user.activated? %>
      <div class="field">
          <div class="ui mini buttons">
            <%= f.submit "Save as Draft", class: "ui button"%>
            <div class="or"></div>
            <%= f.submit "Submit", class: "ui positive button", onclick: 'return submission_alert();' %>
          </div>
      </div>
    <% else %>
      <%= f.submit "Save as Draft", class: "ui button"%>
    <% end %>
    <%=  f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/proposals/edit.html.erb
<div class="ui container grid center aligned">
    <div class="row">
        <div class="ten wide column">
            <div class="ui large header">Edit Proposal</div>
            <div class="ui segment">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/proposals/index.html.erb
<div class="ui container grid center aligned">
    <div class="row">
        <div class="fourteen wide column">
          <% if current_user %>
            <div class="ui basic segment">
                <div class="ui medium header">
                    <% if current_user.type == "Researcher" %>
                    My <% end %> Proposals
                </div>
                <table class="ui orange striped selectable celled table">
                  <thead>
                    <tr><th>Title</th>
                    <% if can? :index, Proposal %>
                      <th>Pricinipal Researcher</th>
                    <% end %>
                    <th class="three wide">Status</th>
                    <% if can? :vote, Proposal %>
                      <th class="three wide">Vote</th>
                    <% elsif can? :veto, Proposal %>
                      <th class="three wide">Veto</th>
                    <% elsif can? :create, Review %>
                      <th class="three wide">Vote</th>
                    <% end %>
                    <th class="four wide">Actions</th>
                  </tr></thead>
                  <tbody>
                    <% @proposals.each do |proposal| %>
                        <% if proposal.status == 2 %>
                        <tr class="positive">
                        <% elsif proposal.status == -1 %>
                        <tr class="negative">
                        <% elsif proposal.status == 1 %>
                        <tr class="warning">
                        <% end %>
                        <td>
                          <div class="ui small header">
                          <%= proposal.title %>
                          </div>
                        </td>
                        <% if can? :index, Proposal %>
                          <td>
                            <%= proposal.principal_researcher %>
                          </td>
                        <% end %>
                        <% if proposal.is_draft%>
                        <td> Draft </td>
                        <% else %>
                          <td><%= @proposal_status[proposal.status] %></td>
                        <% end %>
                        <% if can? :vote, Proposal %>
                          <% if !proposal.head_vote.nil? %>
                            <td>
                            <% if proposal.head_vote == -1 %>
                              <div class="ui label red horizontal">Reject</div>
                            <% elsif proposal.head_vote == 1 %>
                              <div class="ui label orange horizontal">Resubmit</div>
                            <% elsif proposal.head_vote == 2 %>
                              <div class="ui label green horizontal">Accept</div>
                            <% end %>
                            </td>
                          <% else %>
                            <td>Pending</td>
                          <% end %>
                        <% elsif can? :veto, Proposal %>
                          <% if proposal.head_vote == 1 %>
                            <td>
                            <% if proposal.status == -1 %>
                              <div class="ui label red horizontal">Reject</div>
                            <% elsif proposal.status == 2 %>
                              <div class="ui label green horizontal">Accept</div>
                            <% end %>
                            </td>
                          <% else %>
                            <td>Pending</td>
                          <% end %>
                        <% elsif can? :create, Review %>
                          <% committee_review = proposal.reviews.where(user_id: current_user.id).first %>
                          <% if !committee_review.nil? %>
                            <td>
                            <% if committee_review.vote == -1 %>
                              <div class="ui label red horizontal">Reject</div>
                            <% elsif committee_review.vote == 1 %>
                              <div class="ui label orange horizontal">Resubmit</div>
                            <% elsif committee_review.vote == 2 %>
                              <div class="ui label green horizontal">Accept</div>
                            <% end %>
                            </td>
                          <% else %>
                          <td>Pending</td>
                          <% end %>
                        <% end %>
                        <td>
                          <%= link_to "View", proposal_path(proposal), class: "ui mini orange button" %>
                          <% if can? :update, proposal %>
                            <%= link_to "Edit", edit_proposal_path(proposal), class: "ui primary mini button" %>
                          <% end %>
                          <% if can? :cancel, proposal %>
                            <%= link_to "Cancel", cancel_proposal_path(id: proposal.id), method: :post, class: "ui negative mini button" %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
            </div>
            <% else %>
              <div class="ui medium header">Accepted Proposals</div>
              <div class="ui basic segment">
                <%= form_tag search_proposal_path, :method => 'get' do %>
                  <div class="ui input">
                    <%= text_field_tag :search, params[:search], placeholder: 'Search' %>
                  </div>
                  <%= submit_tag "Search", :name => nil, class: 'ui orange button' %>
                <% end %>
              </div>
              <div class="ui segment text">
                <div class="ui divided list">
                  <% @proposals.each do |proposal| %>
                    <div class="item">
                      <div class="content">
                        <div class="header"><%= proposal.title %></div>
                        <%= proposal.principal_researcher %>
                      </div>
                    </div>
                  <% end %>
                  <% if @proposals.empty? %>
                  <div class="item">
                    <div class="content">
                      <div class="header">No proposals found.</div>
                    </div>
                  </div>
                  <% end %>
                </div>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/proposals/new.html.erb
<div class="ui container grid center aligned">
    <div class="row">
        <div class="ten wide column">
            <div class="ui large header">Submit Proposal</div>
            <div class="ui segment">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/proposals/show.html.erb
<div class="ui container text proposal content">
  <div class="ui segment">
    <div class="ui grid">

      <div class="one column row">
        <div class="column">
          <h2 class="ui header">
            <div class="sub header">
            Title of Project:
            </div>
            <%= @proposal.title %> 
          </h2>
        </div>
      </div>

      <div class="two column row">
        <div class="column">
          <h3 class="ui medium header">
            <div class="sub header">
            Principal Researcher:
            </div>
            <%= @proposal.principal_researcher %>
          </h3>
        </div>
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Total Research and Development Cost
            </div>
            <%= @proposal.rdCost %>
          </div>
        </div>
      </div>

      <div class="two column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Name of Coresearchers:
            </div>
            <%= @proposal.coresearchers.present? ? @proposal.coresearchers : 'N/A' %>
          </div>
        </div>
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Source of External Funds:
            </div>
            <%= @proposal.sourceExternal.present? ? @proposal.sourceExternal : 'N/A'%>
          </div>
        </div>
      </div>

      <div class="two column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Facilities, Materials, Staff within the Department or College (if any):
            </div>
            <%= @proposal.facMat.present? ? @proposal.facMat : 'N/A'%>
          </div>
        </div>
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Amount of External Funds:
            </div>
            <%= @proposal.amountExternal.present? ? @proposal.amountExternal : 'N/A'%>
          </div>
        </div>
      </div>

      <div class="one column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Description of Work Done and Accomplishemnts (if project is in progress):
            </div>
            <%= @proposal.description.present? ? @proposal.description : 'N/A'%>
          </div>
        </div>
      </div>

      <div class="one column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Objectives of the Project:
            </div>
            <%= @proposal.objectives.present? ? @proposal.objectives : 'N/A'%>
          </div>
        </div>
      </div>

      <div class="two column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Expected Outputs:
            </div>
            <%= @proposal.expectedOutputs.present? ? @proposal.expectedOutputs : 'N/A'%>
          </div>
        </div>
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Estimated Number of Hours Per Week Devoted to this Project:
            </div>
            <%= @proposal.weeklyHours.present? ? @proposal.weeklyHours : 'N/A'%>
          </div>
        </div>
      </div>
      
      <div class="one column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Have you attained endorsement from Department Head/Chairman?: 
            <i class="icon <%= @proposal.endorsement.present? ? 'checkmark': 'remove' %>"></i> 
            </div>
          </div>
        </div>
      </div>

      <div class="one column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            Have you submitted this proposal to any other funding agency?: 
            <i class="icon <%= @proposal.submitAgency.present? ? 'checkmark': 'remove' %>"></i> 
            </div>
          </div>
        </div>
      </div>

      <div class="one column row">
        <div class="column">
          <div class="ui tiny header">
            <div class="sub header">
            List of Agencies:
            </div>
            <%= @proposal.listAgency.present? ? @proposal.listAgency : 'N/A'%>
          </div>
        </div>
      </div>
      
   
      <div class="row centered" style="margin-bottom: 10px;">
        <div class="six wide column right aligned">
          <%= link_to @proposal.attachment.url, class: 'ui mini button green' do %>
            <i class="icon arrow down"></i>Download Proposal
          <% end %>
        </div>
        <div class="six wide column">
          <%= link_to @proposal.recommendation.url, class: 'ui mini button green' do %>
            <i class="icon arrow down"></i>Download Recommendation
          <% end %>
        </div>
      </div>

      <!--
      <%= link_to 'Edit', edit_proposal_path(@proposal) %> |
      <%= link_to 'Back', proposals_path %>
      -->
    </div>
  </div>

  <% if can?(:create, Review) && current_user.reviews.where('proposal_id = ?', @proposal.id).length < 1 %>
    <div class="ui divider"></div>
    <div class="ui segment">
      <%= form_for @review, html: { class: 'ui form' } do |f| %>
        <div class="field">
          <%= f.label :comment, "Comment" %>
          <%= f.text_area :comment, rows: 2%>
        </div>
        <div class="field">
          <%= f.label :attachment, "Review PDF" %>
          <%= f.file_field :attachment, accept: '.pdf'%>
        </div>
        <div class="ui grid" style="margin-bottom: 5px;">
          <div class="two column row centered">
            <div class="column center aligned">
              <%= f.submit 'Accept', class: 'ui button green small' %>
              <%= f.submit 'Resubmit', class: 'ui button orange small' %>
              <%= f.submit 'Reject', class: 'ui button red small' %>
            </div>
          </div>
        </div>
        <%= f.hidden_field :proposal_id, value: @proposal.id %>
      <% end %>
    </div>  

  <% elsif can? :read, @current_review %>
    <div class="ui divider"></div>
    <div class="ui segment">
      <div class="ui grid">

        <div class="one column row">
          <div class="column">
            <h2 class="ui header">
              <div class="sub header">
              Vote:
              <% if @current_review.vote == -1 %>
                <div class="ui label red horizontal">Reject</div>
              <% elsif @current_review.vote == 1 %>
                <div class="ui label orange horizontal">Resubmit</div>
              <% elsif @current_review.vote == 2 %>
                <div class="ui label green horizontal">Accept</div>
              <% end %>
              </div>
            </h2>
          </div>
        </div>

        <div class="one column row">
          <div class="column">
            <h4 class="ui header">
              <div class="sub header">
              Comment:
              </div>
              <%= @current_review.comment.present? ? @current_review.comment : 'N/A' %> 
            </h4>
          </div>
        </div>

        <% if @current_review.attachment.present? %>
          <div class="column row centered" style="margin-bottom: 10px;">
            <div class="column center aligned">
                <%= link_to @current_review.attachment.url, class: 'ui button green small' do %>
                  <i class="icon arrow down"></i>Download Review
                <% end %>
            </div>
          </div>
        <% end %>

      </div>

    </div>
  <% elsif can? :vote, Proposal %>
    <div class="ui divider"></div>
    <% @reviews.each do |review| %>
      <div class="ui segment">
        <div class="ui grid">

         <div class="one column row">
            <div class="column">
              <h4 class="ui header">
                <div class="sub header">
                Committee Member: 
                </div>
                <%= review.user.full_name %>
              </h4>
            </div>
          </div>

          <div class="one column row">
            <div class="column">
              <h2 class="ui header">
                <div class="sub header">
                Vote:
                <% if review.vote == -1 %>
                  <div class="ui label red horizontal">Reject</div>
                <% elsif review.vote == 1 %>
                  <div class="ui label orange horizontal">Resubmit</div>
                <% elsif review.vote == 2 %>
                  <div class="ui label green horizontal">Accept</div>
                <% end %>
                </div>
              </h2>
            </div>
          </div>

          <div class="one column row">
            <div class="column">
              <h4 class="ui header">
                <div class="sub header">
                Comment:
                </div>
                <%= review.comment.present? ? review.comment : 'N/A' %> 
              </h4>
            </div>
          </div>

          <% if review.attachment.present? %>
            <div class="column row centered" style="margin-bottom: 10px;">
              <div class="column center aligned">
                  <%= link_to review.attachment.url, class: 'ui button green small' do %>
                    <i class="icon arrow down"></i>Download Review
                  <% end %>
              </div>
            </div>
          <% end %>

        </div>
      </div>
      <% end %>
      <div class="ui segment">
        <div class="ui grid">
          <div class="two column row centered" style="margin-bottom: 10px;">
            <div class="column center aligned">
              <% if @proposal.head_vote.present? %>
                <div class="one column row">
                  <div class="column">
                    <h2 class="ui header">
                      <div class="sub header">
                      Your vote:
                      <% if @proposal.head_vote == -1 %>
                        <div class="ui label red horizontal">Reject</div>
                      <% elsif @proposal.head_vote == 1 %>
                        <div class="ui label orange horizontal">Resubmit</div>
                      <% elsif @proposal.head_vote == 2 %>
                        <div class="ui label green horizontal">Accept</div>
                      <% end %>
                      </div>
                    </h2>
                  </div>
                </div>
              <% else %>
              <h3 class="ui header" style="margin-bottom: -10px;">Vote</h3>
                <%= link_to 'Accept', head_vote_path(:proposal_id => @proposal.id, vote: 'Accept'), class: 'ui button green small' %>
                <%= link_to 'Resubmit', head_vote_path(:proposal_id => @proposal.id, vote: 'Resubmit'), class: 'ui button orange small' %>
                <%= link_to 'Reject', head_vote_path(:proposal_id => @proposal.id, vote: 'Reject'), class: 'ui button red small' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

  <% if can? :veto, @proposal %>
    <div class="ui segment">
      <div class="ui grid">
        <div class="two column row centered" style="margin-bottom: 10px;">
          <div class="column center aligned">
            <% if @proposal.head_vote.present? && @proposal.status != 0 %>
              <div class="one column row">
                <div class="column">
                  <h2 class="ui header">
                    <div class="sub header">
                    Your vote:
                    <% if @proposal.status == -1 %>
                      <div class="ui label red horizontal">Reject</div>
                    <% elsif @proposal.status == 2 %>
                      <div class="ui label green horizontal">Accept</div>
                    <% end %>
                    </div>
                  </h2>
                </div>
              </div>
            <% else %>
            <h3 class="ui header">Veto</h3>
              <%= link_to 'Accept', veto_path(:proposal_id => @proposal.id, vote: 'Accept'), class: 'ui button green small' %>
              <%= link_to 'Reject', veto_path(:proposal_id => @proposal.id, vote: 'Reject'), class: 'ui button red small' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>