config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :proposals
  resources :reviews
  resources :votes

  root :to => 'landing_page#index'

  post '/proposal/cancel' => 'proposals#cancel', as: 'cancel_proposal'
  get '/submission_period/toggle' => 'submission_periods#toggle', as: 'toggle_submission_period'
  get '/proposal/vote' => 'proposals#head_vote', as: 'head_vote'
  get '/proposal/veto' => 'proposals#veto', as: 'veto'
  get '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/activate' => 'users#activate', as: 'activate_user'
  get '/users/:id/deactivate' => 'users#deactivate', as: 'deactivate_user'
  get '/proposal/search' => 'proposals#search', as: 'search_proposal'
  resources :announcements, except: [:index]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
      @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    authorize! :create, Review
    @review = Review.new(review_params)
    if current_user.reviews.where('proposal_id = ?', @review.proposal_id).length > 0
      flash[:negative] = "You can only give a review once per proposal"
      redirect_to :back and return
    end
    @review.user_id = current_user.id

    if params[:commit] == "Reject"
      @review.vote = -1
    elsif params[:commit] == "Accept"
      @review.vote = 2
    elsif params[:commit] == "Resubmit"
      @review.vote = 1
    end
    
    @review.save

    redirect_to :back
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to reviews_path
  end

  private
    def review_params
      params.require(:review).permit(:attachment, :vote, :comment, :proposal_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this proposal from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.file_field :attachment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>

<%= link_to 'Back', review_path %>

app/views/reviews/index.html.erb
<h1>Review List</h1>

<table>
  <tr>
    <th>Attachment</th>
    <th>Created Date/time</th>
    <th>Updated Date/time</th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.attachment %></td>
      <td><%= review.created_at%></td>
      <td><%= review.updated_at%></td>

      <td><%= link_to "Download Attachment", review.attachment_url %></td>
    </tr>
  <% end %>
</table>

app/views/reviews/new.html.erb
<h1>Upload Review</h1>
<%= render 'form' %>
<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p>
  <strong>Review file</strong>
  <%= @review.attachment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>